name: Zip Release
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Zip Release
        uses: TheDoctor0/zip-release@0.7.6
        with:
          filename: eMixedNiteMC.pthm # Set the archive name here
          path: . # Specify the base path, or leave as default
          directory: . # Working directory, use default or specify
          exclusions: '' # List any files or directories to exclude
          recursive_exclusions: '' # Exclude with wildcards if needed (Windows with `zip` type only)
          custom: '' # Add custom zip parameters if needed
          type: zip # Choose archiving tool, default is zip
          command: '' # Extra command before zipping, optional
